version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  carPartsShopManagement:
    container_name: carPartsShopManagement
    build:
      context: carPartsShopManagement
      dockerfile: Dockerfile
    image: cps-management:latest
    ports:
      - "8082:8082"
    depends_on:
      - kafka
  carPartsShopDisplay:
    container_name: carPartsShopDisplay
    build:
      context: carPartsShopDisplay
      dockerfile: Dockerfile
    image: cps-display:latest
    ports:
      - "8083:8083"
    depends_on:
      - kafka