version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092, OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092, OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper
  carPartsShopManagement:
    container_name: carPartsShopManagement
    build:
      context: carPartsShopManagement
      dockerfile: Dockerfile
    image: cps-management:latest
    ports:
      - "8082:8082"
    depends_on:
      - kafka
  carPartsShopDisplay:
    container_name: carPartsShopDisplay
    build:
      context: carPartsShopDisplay
      dockerfile: Dockerfile
    image: cps-display:latest
    ports:
      - "8083:8083"
    depends_on:
      - kafka